# Changes here will be overwritten by Copier
_commit: v0.1.1
_src_path: gh:edgarrmondragon/singer-tap-copier-template
author_email: edgarrmondragon@hey.com
author_fullname: Edgar Ramírez
author_username: edgarrmondragon
dependabot_update_time: '10:00'
dependabot_update_timezone: Etc/UTC
python_main_version: '3.12'
repository_name: tap-toggl
repository_namespace: edgarrmondragon
repository_provider: github.com
repository_visibility: public
tap_auth_method: Basic Auth
tap_id: tap-toggl
tap_package_command_line_name: tap-toggl
tap_package_distribution_name: tap-toggl
tap_package_import_name: tap_toggl
tap_source_description: Time Tracking Software for Any Workflow
tap_source_id: Toggl
tap_source_name: Toggl
tap_stream_type: REST
vscode_files: true
